version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.3.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama
